sonar.projectKey=oficina-mecanica-api
sonar.projectName=Oficina Mecanica API
sonar.host.url=http://localhost:9000
sonar.token=SEU_TOKEN

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8