apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${KUBERNETES_NAMESPACE}
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - hpa.yaml
  - ../../base
images:
  - name: fase2-kubernetes-oficina-mecanica-api
    newName: ${ECR_REPOSITORY_URL}
    newTag: ${API_IMAGE_TAG}
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: fase2-kubernetes-oficina-mecanica-api
