apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oficina-mecanica
resources:
  - namespace.yaml
  - postgres.yaml
  - api.yaml
  - migration-job.yaml
configMapGenerator:
  - name: postgres-config
    literals:
      - POSTGRES_DB=oficina_mecanica
      - POSTGRES_USER=oficina
  - name: api-config
    literals:
      - NODE_ENV=development
      - APP_PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=oficina_mecanica
      - POSTGRES_SYNC=0
      - POSTGRES_SSL=0
      - POSTGRES_SSL_REJECT_UNAUTHORIZED=0
      - JWT_EXPIRES_IN=1h
      - RESEND_FROM=onboarding@resend.dev
      - NOTIFICACAO_EMAIL_MECANICOS=local@example.com
      - NOTIFICACAO_EMAIL_ADMIN=local@example.com
secretGenerator:
  - name: postgres-secret
    literals:
      - POSTGRES_PASSWORD=oficina-local
  - name: api-secret
    literals:
      - POSTGRES_USER=oficina
      - POSTGRES_PASSWORD=oficina-local
      - JWT_SECRET=jwt-secret-apenas-para-desenvolvimento-local
      - RESEND_API_KEY=re_chave-ficticia-para-desenvolvimento-local
generatorOptions:
  labels:
    app.kubernetes.io/part-of: oficina-mecanica
